name: Update data
on:
  schedule:
    - cron: "0 9 * * *"   # daily at 09:00 UTC
  workflow_dispatch:        # manual run button
jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: |
          echo '{}' > data/.keep.json
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add -A && git commit -m "bootstrap data folder" && git push
          fi
